
public enum DialogueVar
{
    None,
    PizzaEaten,
    PerkinsWalkWithLin,
    PerkinsWalkerFixed,
    PerkinsGoesWalk,
    SethPartsGained,
    SethLeaveNotified,
    PizzaRecall,
    PerkinsLinConnection,
    LinSethConnection,
    SethPerkinsConnection,
    SethFinalDayChoice,
    LinFinalDayChoice,
    MrsPerkinsFinalDayChoice,
    PerkinsVolunteers,
    PerkinsStays,
    HowardMessageHeard,
    LinStays,
    SethCloses,
    OlsonCallLin,
    PerkinsCalledByLin,
    PerkinsCalledBySeth,
    PretzelStandFixed,
    TutorialComplete,
    TutorialButton
}
